### ISSUE TITLE
Multiple display rendering issue?

### ISSUE THREAD

**Issue by patridge** [PapaMufflon/CodeNinjaSpy#1]
If I have my desktop extend across multiple displays, it doesn't appear to display anything after the loading is complete and I start hitting keyboard shortcuts.

If I quit VS, switch to mirrored displays, and run VS again, it works fine.

**Comment by PapaMufflon** [comment]
Can you compile the newest code and try to reproduce this bug? I've added a simple logger to be able to find such bugs. Just activate it by clicking in the lower left corner and a button reading "Debug is on" should appear. The log is a text-file with name "CodeNinjaSpyLog.txt" and should reside in the folder [Users][YourUser]\AppData\Roaming.

**Comment by patridge** [comment]
The newest code doesn't appear to have this issue. Though now I get a "Ctrl+/" (Edit.GoToFindCombo) put in the queue whenever I move the mouse.

Getting the "Debug is on" button also required popping it to its own window and then clicking the corner (I had it mounted as a portion of a side bar.

**Comment by PapaMufflon** [comment]
Cool :)
I'm planning to give an opportunity to stop displaying annoying commands like Ctrl+/ and Ctrl+# in the future.
As the debug-"feature" should be as invisible as possible, I like it, that you have to undock it to be able to click that button. I should have tested it better, though!
But thank you for testing the current version :)
